from . import hotel_room
from . import hotel_service
from . import hotel_evaluate
from . import hotel_promotion
from . import holel_room_type
from . import hotel_reservation_form
from . import hotel_service_detail
from . import hotel_staff
from . import hotel_position
from . import hotel_room_rental_details
from . import hotel_bill_detail
